SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT
    LINE
FROM (
    SELECT
        ORD = 1,
        LINE = 'HDR,CLASS,LETTER,SEND,CALLMETHOD'
	UNION SELECT
        ORD = 2,
        LINE = 'COL,Letter,Send Method,Account'
	UNION SELECT
        ORD = 3,
		LINE = 'DET, BOOSTTOPAYM1, AUTO,' + CONVERT(VARCHAR, A.ACCTNO)
		FROM ACCOUNTS A
		WHERE A.ACCTNO IN ('2643521') --insert account numbers here
	)
LINES
ORDER BY
    ORD