SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT
    LINE
FROM (
    SELECT
        ORD = 1,
        LINE = 'HDR,CLASS,CONSUMER.CONTRACT,CREATE,CREATEINSTANCE'
	UNION SELECT
        ORD = 2,
        LINE = 'COL,Consumer,Plan,Effective Date'
	UNION SELECT
        ORD = 3,
		LINE = 'DET,' + CONVERT(VARCHAR, C.CONSUMERNO) + ',OE' + 
		CASE
			WHEN SUBSTRING(CURR.ECPLAN_KEY, LEN(CURR.ECPLAN_KEY)-2, LEN(CURR.ECPLAN_KEY)) = '_25' THEN SUBSTRING(CURR.ECPLAN_KEY, 3, LEN(CURR.ECPLAN_KEY)-5) + '_17'
			WHEN SUBSTRING(CURR.ECPLAN_KEY, LEN(CURR.ECPLAN_KEY)-3, LEN(CURR.ECPLAN_KEY)) = '_DCC' THEN SUBSTRING(CURR.ECPLAN_KEY, 3, LEN(CURR.ECPLAN_KEY)-6) + '_17'
         ELSE SUBSTRING(CURR.CCON_PLANID1, 3, LEN(CURR.CCON_PLANID1))
		END
		+ ',ADDDATEHERE' --update contract start date here
		FROM ACCOUNTS A
		INNER JOIN CONSUMER C ON C.CACCT = A.ACCTNO
		OUTER APPLY 
			(
			SELECT TOP 1 * FROM EMS_CON_CONTRACT ECC
			JOIN EMS_CON_PLAN ECP ON ECP.ECPLAN_KEY = ECC.CCON_PLANID1
			WHERE ECC.CCON_CONSUMER = C.CONSUMERNO
			AND ECC.CCON_ACTIVE != 'C'
			ORDER BY ECC.CCON_STARTDATE DESC
			) CURR
		WHERE A.ACCTNO IN ('2643521') --insert account numbers here
		AND C.CSTATUSTYPE < 40 
	)
LINES
ORDER BY
    ORD