-- Description: Query for finding accounts with PAN and DCC enabled meters 

Select DISTINCT CACCT AS Account, 
			    CONSUMERNO AS consumer,
                CINSTALL AS INSTALL,
                ICP_IDENT AS MPXN,
                INETWCONN AS GSP,
                IUTILITYTYPE AS UTILITY
				FROM CONSUMER
	LEFT OUTER JOIN INSTALL ON CINSTALL = INSTALL
	LEFT OUTER JOIN DAHISTORY DAH ON INSTALL = DAH.DAH_INSTALL
	LEFT OUTER JOIN PREPAYCARD ON CONSUMERNO = PREPAYCARD.PC$CONSUMER
	LEFT OUTER JOIN DAMETHISTORY  ON INSTALL = DAMH$INSTALL
	LEFT OUTER JOIN CCSERVICEORDER ON SOACCOUNT = CACCT


	where DAH.DAH_METERCOMM = 'A' -- DCC Enabled = 'A'/ DCC disabled IS NULL
    AND CSTATUSTYPE = '30' -- LIVE = '30' / Final = '40' 
	AND PREPAYCARD.PC$CONSUMER IS NOT NULL
	AND PC$REMOVEDATE IS NULL
	AND DAMH$INSTALL$CODE = 'S1' 
	AND SOSTATUS = '91'


