SELECT DISTINCT
    LPTRAN.LPT$LEDGER AS Account,
    LPTRAN_ARC.LPT$AMOUNT/100 AS ArchiveAmount,
    LPTRAN.LPT$AMOUNT/100 AS CurrentAmount,
    LETDATE AS letterDate,
	LPTRAN_ARC.LPT$DUEDATE AS ArchiveDate
FROM
    LPTRAN_ARC
    
JOIN LPTRAN ON LPTRAN_ARC.LPT$LEDGER = LPTRAN.LPT$LEDGER
JOIN CONSUMER ON LPTRAN.LPT$LEDGER = CACCT
JOIN LET_FORMATDATAARC ON CACCT = LETID_ACC
WHERE
    CSTATUSTYPE = '30'
    AND LETCODE_CODE = 'XMLBCDD'
    AND LETDATE BETWEEN '2022-09-20' AND '2023-09-21'

ORDER BY ArchiveDate DESC