-- Queries used for GENU-1330 - Testing for Process HK.DOCBDATA

SELECT COUNT(DOCBD$DATAID) AS DOCBDATARecords FROM DOCBDATA

SELECT COUNT(DOCBH$SEQNO) AS DOCBHEADERRecords FROM DOCBHEADER
WHERE DOCBH$SYSDATETIME <= DATEADD(DAY, -180, GETDATE())

SELECT COUNT(DOCBD$DATAID) AS recordsOver6Months FROM DOCBHEADER
JOIN DOCBDATA ON DOCBD$DATAID = DOCBH$DATAID
WHERE DOCBH$SYSDATETIME <= DATEADD(DAY, -180, GETDATE())


SELECT * FROM EMSNEXTDATE