-- Queries used for GENU-1330 

SELECT COUNT(DOCBD$DATAID) AS totalNumberOfEnteries FROM DOCBDATA

SELECT COUNT(DOCBD$DATAID) AS recordsOver6Months FROM DOCBHEADER
JOIN DOCBDATA ON DOCBD$DATAID = DOCBH$DATAID
WHERE DOCBH$SYSDATETIME <= DATEADD(DAY, -180, GETDATE())


SELECT * FROM EMSNEXTDATE