-- Description: Query used to see the phase 1 erasure has completed on the tables 

SELECT ACNAME, ACTRADINGNAME, ACABNNO, ACMARKETING, ACCOMMENTS, ACPASSWORD_DATA, ACPASSWORD_TYPE, LP$CUSTREF,LP$INSTRUCTION$REF
   LP$NAME,
   LP$BANK,
   LP$CREDITCARD,
   LP$CREDITEXPIRY,
   LP$CREDITENCRYPT,
   LP$AGREENO FROM ACCOUNTS 

FULL JOIN CUSTOMERROLE ON CUSR_ACCTNO = ACCTNO
FULL JOIN CUSTOMER ON CUS_SEQNO = CUSR_SEQNO
FULL JOIN LEDGERPAY ON LP$LEDGER = ACCTNO
FULL JOIN LPTRAN ON LPT$LEDGER = LP$LEDGER
--FULL JOIN LPTRAN_BANK ON LPBK$LEDGER = LP$LEDGER

WHERE ACCTNO IN ('3084272',
'6149989',
'2592667')

-- Description: Query used to find eligible accounts for erasure
-- Must be over 6 years after finalled date with no outstanding actions on account 

SELECT acc.ACCTNO,con.CSTATUSTYPE,con.CONSUMERNO,con.CDFINAL,con.CCRITICALCODE, acc.ACPAYMETHOD ,acc.ACNAME FROM ACCOUNTS acc 
INNER JOIN CONSUMER con ON con.CACCT = acc.ACCTNO
WHERE con.CSTATUSTYPE = '40'
and exists
(
SELECT top 1 *
FROM [Gen_PreProd].[dbo].[ACCOUNTS] acct
INNER JOIN [Gen_PreProd].[dbo].[CONSUMER] cons ON cons.CACCT = acct.ACCTNO
INNER JOIN [Gen_PreProd].[dbo].[CUSTOMERROLE] crol on crol.CUSR_ACCTNO=acct.ACCTNO
INNER JOIN [Gen_PreProd].[dbo].[CUSTOMER] cust ON crol.CUSR_CUSTOMER=cust.CUS_SEQNO
WHERE cons.CDFINAL <= DATEADD(year,-6,GETDATE()) -- consumer ended 6 years ago
AND CSTATUSTYPE = '40' -- FOR FINALLED ACCOUNTS
AND acc.ACCTNO=acct.ACCTNO
)

-- To find the customerseqno for the account number

SELECT ACCTNO, CUSR_CUSTOMER FROM ACCOUNTS
FULL JOIN CUSTOMERROLE ON CUSR_ACCTNO = ACCTNO 
FULL JOIN CUSTOMER ON CUS_SEQNO = CUSR_CUSTOMER

WHERE ACCTNO IN ('2102716',
'2102723',
'2102723',
'2102730',
'2102741')

