SELECT COUNT(DISTINCT LOCA_ITEMID) AS NoOfInstalls, MAX(LOCA_ITEMID) AS InstallNo, MAX(ICP_IDENT) AS MPAN, CBILLCLASS, LOCA_HOUSE, LOCA_STREET, LOCA_POSTCODE FROM LOCADDRESS 
INNER JOIN GenProd.dbo.INSTALL ON INSTALL = LOCA_ITEMID
INNER JOIN GenProd.dbo.CONSUMER ON ICONSUMER = CONSUMERNO
INNER JOIN genprod.dbo.CCSERVICEORDER ON SOCONSUMER = CONSUMERNO
WHERE LOCA_HOUSE IS NOT NULL AND LOCA_STREET IS NOT NULL AND LOCA_POSTCODE IS NOT NULL 
AND LOCA_LABEL = 'INSTALL' AND LOCA_ITEMID IS NOT NULL AND IUTILITYTYPE = 'E' AND CSTATUSTYPE = '30'
--AND CBILLCLASS = 'PAYG' -- PAYM - 'DOM' & PAYG - 'PAYG'
AND SOTYPE NOT IN ('COT|MOVEOUT', 'S1UKLOSS|DEREGISTRATION','AUK_LOSS')
GROUP BY LOCA_POSTCODE,LOCA_STREET,LOCA_HOUSE,CBILLCLASS,IUTILITYTYPE,LOCA_FREEFORM,LOCA_UNIT,LOCA_BUILDING,LOCA_HOUSEPREFIX
HAVING COUNT(DISTINCT LOCA_ITEMID) > 1 
ORDER BY COUNT(LOCA_ITEMID) DESC;


