-- Description: This script is used to get the number of consumers per tariff 
-- Used for Variable Price Change Tariff Testing

SELECT CON.CCON_PLANID1, COUNT(C.CONSUMERNO) AS NoOfConsumers FROM CONSUMER C
OUTER APPLY (
	SELECT TOP 1 * 
	FROM EMS_CON_CONTRACT CON
	WHERE CON.CCON_ACTIVE <> 'C'
	AND CON.CCON_CONSUMER = C.CONSUMERNO
	ORDER BY CON.CCON_STARTDATE DESC
) CON

WHERE C.CSTATUSTYPE = '30'

AND (CCON_PLANID1 LIKE 'PA_E_%_DCC'
OR CCON_PLANID1 LIKE 'PA_G_%_DCC'
OR CCON_PLANID1 LIKE 'PA_E_%_17'
OR CCON_PLANID1 LIKE 'PA_G_%_17'
OR CCON_PLANID1 LIKE 'OE_E_%_17'
OR CCON_PLANID1 LIKE 'OE_G_%_17'
OR CCON_PLANID1 LIKE 'OE_E_%_01'
OR CCON_PLANID1 LIKE 'OE_G_%_01'
OR CCON_PLANID1 LIKE 'OE_E_%_19'
OR CCON_PLANID1 LIKE 'OE_G_%_19')

GROUP BY CON.CCON_PLANID1
ORDER BY NoOfConsumers DESC

